######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 14 17:32:00 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
