/* Auto-generated by genmsg_cpp for file /home/sibi/sandbox/sandbox444/surgical_msgs/msg/InitInfo.msg */
#ifndef SURGICAL_MSGS_MESSAGE_INITINFO_H
#define SURGICAL_MSGS_MESSAGE_INITINFO_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "surgical_msgs/Hole.h"
#include "surgical_msgs/Cut.h"
#include "sensor_msgs/PointCloud2.h"

namespace surgical_msgs
{
template <class ContainerAllocator>
struct InitInfo_ {
  typedef InitInfo_<ContainerAllocator> Type;

  InitInfo_()
  : holes()
  , cuts()
  , cloud()
  {
  }

  InitInfo_(const ContainerAllocator& _alloc)
  : holes(_alloc)
  , cuts(_alloc)
  , cloud(_alloc)
  {
  }

  typedef std::vector< ::surgical_msgs::Hole_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::surgical_msgs::Hole_<ContainerAllocator> >::other >  _holes_type;
  std::vector< ::surgical_msgs::Hole_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::surgical_msgs::Hole_<ContainerAllocator> >::other >  holes;

  typedef std::vector< ::surgical_msgs::Cut_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::surgical_msgs::Cut_<ContainerAllocator> >::other >  _cuts_type;
  std::vector< ::surgical_msgs::Cut_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::surgical_msgs::Cut_<ContainerAllocator> >::other >  cuts;

  typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _cloud_type;
   ::sensor_msgs::PointCloud2_<ContainerAllocator>  cloud;


  typedef boost::shared_ptr< ::surgical_msgs::InitInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::surgical_msgs::InitInfo_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct InitInfo
typedef  ::surgical_msgs::InitInfo_<std::allocator<void> > InitInfo;

typedef boost::shared_ptr< ::surgical_msgs::InitInfo> InitInfoPtr;
typedef boost::shared_ptr< ::surgical_msgs::InitInfo const> InitInfoConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::surgical_msgs::InitInfo_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::surgical_msgs::InitInfo_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace surgical_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::surgical_msgs::InitInfo_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::surgical_msgs::InitInfo_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::surgical_msgs::InitInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "47565f315bb0e1a0dffdb25437d7b98a";
  }

  static const char* value(const  ::surgical_msgs::InitInfo_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x47565f315bb0e1a0ULL;
  static const uint64_t static_value2 = 0xdffdb25437d7b98aULL;
};

template<class ContainerAllocator>
struct DataType< ::surgical_msgs::InitInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "surgical_msgs/InitInfo";
  }

  static const char* value(const  ::surgical_msgs::InitInfo_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::surgical_msgs::InitInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Defines CUTS and HOLES and the reference point-cloud\n\
\n\
# Holes are a bunch of 3D points\n\
Hole[] holes\n\
\n\
# An array of cut is cuts. A cut is an array of 3D points.\n\
Cut[] cuts\n\
\n\
# The cloud on which the holes and cuts are defined\n\
sensor_msgs/PointCloud2 cloud\n\
================================================================================\n\
MSG: surgical_msgs/Hole\n\
# Defines the various attributes of a HOLE\n\
# ----------------------------------------\n\
#\n\
# 1. PT : the 3D location of the HOLE\n\
geometry_msgs/Point pt\n\
\n\
# 2. X_IDX : the x-index of the location of the point in the point-cloud\n\
int32 x_idx\n\
\n\
# 3. Y_IDX : the y-index of the location of the point in the point-cloud\n\
int32 y_idx\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: surgical_msgs/Cut\n\
# defines an array for 3D points.\n\
Hole[] nodes\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
\n\
";
  }

  static const char* value(const  ::surgical_msgs::InitInfo_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::surgical_msgs::InitInfo_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.holes);
    stream.next(m.cuts);
    stream.next(m.cloud);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct InitInfo_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::surgical_msgs::InitInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::surgical_msgs::InitInfo_<ContainerAllocator> & v) 
  {
    s << indent << "holes[]" << std::endl;
    for (size_t i = 0; i < v.holes.size(); ++i)
    {
      s << indent << "  holes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::surgical_msgs::Hole_<ContainerAllocator> >::stream(s, indent + "    ", v.holes[i]);
    }
    s << indent << "cuts[]" << std::endl;
    for (size_t i = 0; i < v.cuts.size(); ++i)
    {
      s << indent << "  cuts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::surgical_msgs::Cut_<ContainerAllocator> >::stream(s, indent + "    ", v.cuts[i]);
    }
    s << indent << "cloud: ";
s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.cloud);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SURGICAL_MSGS_MESSAGE_INITINFO_H

