"""autogenerated by genpy from surgical_msgs/Hole.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Hole(genpy.Message):
  _md5sum = "64cb44aecb568b09a90194264446d6fe"
  _type = "surgical_msgs/Hole"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Defines the various attributes of a HOLE
# ----------------------------------------
#
# 1. PT : the 3D location of the HOLE
geometry_msgs/Point pt

# 2. X_IDX : the x-index of the location of the point in the point-cloud
int32 x_idx

# 3. Y_IDX : the y-index of the location of the point in the point-cloud
int32 y_idx


================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

"""
  __slots__ = ['pt','x_idx','y_idx']
  _slot_types = ['geometry_msgs/Point','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pt,x_idx,y_idx

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Hole, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pt is None:
        self.pt = geometry_msgs.msg.Point()
      if self.x_idx is None:
        self.x_idx = 0
      if self.y_idx is None:
        self.y_idx = 0
    else:
      self.pt = geometry_msgs.msg.Point()
      self.x_idx = 0
      self.y_idx = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3d2i.pack(_x.pt.x, _x.pt.y, _x.pt.z, _x.x_idx, _x.y_idx))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pt is None:
        self.pt = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.pt.x, _x.pt.y, _x.pt.z, _x.x_idx, _x.y_idx,) = _struct_3d2i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3d2i.pack(_x.pt.x, _x.pt.y, _x.pt.z, _x.x_idx, _x.y_idx))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pt is None:
        self.pt = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.pt.x, _x.pt.y, _x.pt.z, _x.x_idx, _x.y_idx,) = _struct_3d2i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3d2i = struct.Struct("<3d2i")
